language: node_js

node_js:
  - 9.11
  - 10

before_script:
  - "npm install typescript --global"
  - "npm install nodemon --global"

script:
  - "cd ./src/client/ && npm install"
  - "cd ../../"
  - "yarn prod"
